"""Add coaching_subject and coach_notes to Coaching model and form

Revision ID: f62172b38762
Revises: ac74e38afbb2
Create Date: 2025-05-29 02:54:38.875748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62172b38762'
down_revision = 'ac74e38afbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coachings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coaching_subject', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coach_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coachings', schema=None) as batch_op:
        batch_op.drop_column('coach_notes')
        batch_op.drop_column('coaching_subject')

    # ### end Alembic commands ###
